version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@11

jobs:
  test:
    working_directory: /go/src/github.com/fairwindsops/nova
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./... | tee golint-report.out
            test -z $(go fmt ./...)
      - run:
          name: test
          command: |
            go test -v --bench --benchmem -coverprofile=coverage.txt -covermode=atomic ./pkg/...
            go vet 2> govet-report.out
            go tool cover -html=coverage.txt -o cover-report.html

  release-binary:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - setup_remote_docker
      - run: curl -sL http://git.io/goreleaser | bash
  publish_docs:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run:
          name: Build Docs Site
          command: |
            set -e
            cd ./docs
            npm install
            npm run check-links
            npm run build
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Publish Docs Site to S3
          command: |
            cd ./dist
            aws s3 sync ./ s3://nova.docs.fairwinds.com --delete

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - rok8s/docker_build_and_push:
          name: build-container
          docker-push: false
          password-variable: "fairwinds_quay_token"
          enable_docker_layer_caching: true
          config_file: .circleci/build.config
          requires:
            - test
          filters:
            branches:
              only: /pull\/[0-9]+/
      - rok8s/docker_build_and_push:
          name: build-and-push-container
          docker-push: true
          enable_docker_layer_caching: true
          config_file: .circleci/build.config
          context: org-global
          docker-login: true
          password-variable: "fairwinds_quay_token"
          registry: quay.io
          username: fairwinds+circleci
          requires:
            - test
          filters:
            branches:
              ignore: /pull\/[0-9]+/
            tags:
              ignore: /.*/

  release:
    jobs:
      - publish_docs:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release-binary:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - rok8s/docker_build_and_push:
          name: build-and-push-container
          docker-push: true
          enable_docker_layer_caching: false
          config_file: .circleci/build.config
          context: org-global
          docker-login: true
          password-variable: "fairwinds_quay_token"
          registry: quay.io
          username: fairwinds+circleci
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
