version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@14
  oss-docs: fairwinds/oss-docs@0

executors:
  golang-exec:
    docker:
      - image: cimg/go:1.21

references:
  e2e_config: &e2e_config
    command_runner_image: quay.io/reactiveops/ci-images:v14-bullseye
    kind_node_image: "kindest/node:v1.29.4@sha256:3abb816a5b1061fb15c6e9e60856ec40d56b7b52bcea5f5f1350bc6e2320b6f8"
    executor: golang-exec
    pre_script: e2e/pre.sh
    store-test-results: /tmp/test-results/
    script: e2e/test.sh
    requires:
      - test
    filters:
      branches:
        only: /.*/
      tags:
        ignore: /.*/  
  install_vault: &install_vault
    run:
      name: install hashicorp vault
      command: |
        apk --update add curl yq
        cd /tmp
        curl -LO https://releases.hashicorp.com/vault/1.13.2/vault_1.13.2_linux_amd64.zip
        sha256sum vault_1.13.2_linux_amd64.zip | grep f7930279de8381de7c532164b4a4408895d9606c0d24e2e9d2f9acb5dfe99b3c
        unzip vault_1.13.2_linux_amd64.zip
        mv vault /usr/bin/vault
jobs:
  test:
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - run:
          name: lint
          command: |
            echo "installing golint"
            go install golang.org/x/lint/golint@latest
            echo "linting..."
            golint -set_exit_status ./... | tee golint-report.out
            echo "checking go fmt..."
            if ! test -z $(go fmt ./...); then
              echo "Please run go fmt ./... to format your code"
              exit 1
            fi
      - run:
          name: test
          command: |
            go test -v --bench --benchmem -coverprofile=coverage.txt -covermode=atomic ./pkg/...
            go vet 2> govet-report.out
            go tool cover -html=coverage.txt -o cover-report.html
  snapshot:
    working_directory: /go/src/github.com/fairwindsops/nova
    resource_class: large
    docker:
      - image: goreleaser/goreleaser:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run: goreleaser --snapshot
      - store_artifacts:
          path: dist
          destination: snapshot
  release:
    working_directory: /go/src/github.com/fairwindsops/nova
    resource_class: large
    shell: /bin/bash
    docker:
      - image: goreleaser/goreleaser:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - *install_vault
      - rok8s/get_vault_env:
          vault_path: repo/global/env
      - rok8s/docker_login:
          registry: "quay.io"
          username: $FAIRWINDS_QUAY_USER
          password-variable: FAIRWINDS_QUAY_TOKEN
      - run: echo 'export GORELEASER_CURRENT_TAG="${CIRCLE_TAG}"' >> $BASH_ENV
      - run: goreleaser
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - rok8s/kubernetes_e2e_tests:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          name: functional tests
          <<: *e2e_config
  release:
    jobs:
      - oss-docs/publish-docs:
          repository: nova
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
